# Generated by Django 4.2.1 on 2023-06-13 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='interesse',
            field=models.CharField(choices=[('show', 'Shows de Música'), ('futebol', 'Jogos de Futebol'), ('outros', 'Outros')], max_length=50, verbose_name='Interesse'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
    ]
