# Generated by Django 4.2.1 on 2023-06-13 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_alter_inscricao_email_alter_inscricao_interesse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='data',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data criação'),
        ),
    ]
