# Generated by Django 4.2.1 on 2023-06-20 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_categoria_alter_inscricao_options_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='destaque',
            field=models.BooleanField(blank=True, default=False, verbose_name='Destaque'),
        ),
    ]
